// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADjEn_N0dD2XpTA-2imklypYPNtrBqKl0',
    appId: '1:952763410449:web:0c8e6d6cf47c60417fe9b0',
    messagingSenderId: '952763410449',
    projectId: 'fir-demo-709a9',
    authDomain: 'fir-demo-709a9.firebaseapp.com',
    storageBucket: 'fir-demo-709a9.appspot.com',
    measurementId: 'G-JWE88P2WB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7djTEzxQB97wNKdVX2GgraUhwbF7FVWI',
    appId: '1:952763410449:android:1fbcd09cb8e957467fe9b0',
    messagingSenderId: '952763410449',
    projectId: 'fir-demo-709a9',
    storageBucket: 'fir-demo-709a9.appspot.com',
  );
}
